name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install FrontEnd
        run: |
          cd FrontEnd
          npm install

      - name: Install Backend
        run: |
          cd giftlink-backend
          npm install
